# the same as docker-compose.yaml, but for people who want to build the image
# and run the server on their own PC

version: "2"

services:

  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  otree:
    # if using Docker Hub, leave "build: ./" commented out.
    # if you want to build an image locally, uncomment it.

    build: ./
    image: otree:latest
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DATABASE}"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_PRODUCTION: ${OTREE_PRODUCTION}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
    ports:
      - ${OTREE_PORT}:80
    volumes:
      - "otree-resetdb:/opt/init"
    # Uncomment for live editing
    #  - ./:/opt/otree
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-net
      - redis-net

  redis:
    image: redis
    command: "redis-server"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - redis-net

volumes:
  database:
  otree-resetdb:

networks:
  db-net:
  redis-net:
